### ISSUE TITLE
Run on react-native

### ISSUE THREAD

**Issue by OoDeLally** [Sansossio/twisted#37]
Hello,
I am not able to run it on a react-native project.
```
Failed building JavaScript bundle.
Unable to resolve module os from /home/user/project/node_modules/request-promise/lib/rp.js: os could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  17 | } catch (err) {
  18 |     /* istanbul ignore next */
> 19 |     var EOL = require('os').EOL;
```

I believe the reason is that some of `twisted`'s deps are only available on Node.js.

**How hard would it be to have it running on all platforms?** 

Requests could be done with [Axios](https://github.com/axios/axios), which works on both node and browser.

If you believe it is not a big refactoring, I can give it a try.

**Comment by Sansossio** [comment]
I've change request-promise to axios, request-promise is dead, I just forgot that we were using that library here hehe:
https://github.com/Sansossio/twisted/commit/6f85e62772666eaae154796822492d6b0c0637da

Anyway, I don't know if you will be able to use this library on react native because you cannot use Riot Games Api on frontend environment (you cant do it and you shouldn't do it because that key is linked with your lol account).

New twisted package version: https://github.com/Sansossio/twisted/commit/aded1ffab96e37fedd089251beb02ae0227ecaa5

**Comment by OoDeLally** [comment]
Gosh, you're fast!
I was blocked so I'v made my own package https://github.com/OoDeLally/twisted-axios :sweat_smile: 
There was a bit more things, like
- `querystring` (part of Node.js) => `query-string`
- `camelcasejs` (using a `require()` that doesnt play well) => `camelcase`
- removed `dotenv`

Now, reading your reply, I realize that you are correct that
> you cannot use Riot Games Api on frontend environment

So I'm gonna throw myself out of the window now.

Thanks for your reactivity though, it's really appreciated :-)
